export default Object.freeze({
  FETCH_QUERY: 'FETCH_QUERY',
  FETCH_QUERY_STARTED: 'FETCH_QUERY_STARTED',
  FETCH_QUERY_SUCCESS: 'FETCH_QUERY_SUCCESS',
  FETCH_QUERY_FAILURE: 'FETCH_QUERY_FAILURE',
  SELECT_PRODUCT: 'SELECT_PRODUCT',
  SELECT_PRODUCT_STARTED: 'SELECT_PRODUCT_STARTED',
  SELECT_PRODUCT_SUCCESS: 'SELECT_PRODUCT_SUCCESS',
  SELECT_PRODUCT_FAILURE: 'SELECT_PRODUCT_FAILURE',
  FETCH_USERS: 'FETCH_USERS',
  FETCH_USERS_STARTED: 'FETCH_USERS_STARTED',
  FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
  FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',
  FETCH_COMMENTS: 'FETCH_COMMENTS',
  FETCH_COMMENTS_STARTED: 'FETCH_COMMENTS_STARTED',
  FETCH_COMMENTS_SUCCESS: 'FETCH_COMMENTS_SUCCESS',
  FETCH_COMMENTS_FAILURE: 'FETCH_COMMENTS_FAILURE'
});
