export default Object.freeze({
  FETCH_QUERY: 'FETCH_QUERY',
  FETCH_QUERY_STARTED: 'FETCH_QUERY_STARTED',
  FETCH_QUERY_SUCCESS: 'FETCH_QUERY_SUCCESS',
  FETCH_QUERY_FAILURE: 'FETCH_QUERY_FAILURE',
});
