import constants from './index';

describe('Constants', () => {
  it('should test true', () => {
    expect(constants).toEqual({
      FETCH_QUERY: 'FETCH_QUERY',
      FETCH_QUERY_STARTED: 'FETCH_QUERY_STARTED',
      FETCH_QUERY_SUCCESS: 'FETCH_QUERY_SUCCESS',
      FETCH_QUERY_FAILURE: 'FETCH_QUERY_FAILURE',
      FETCH_QUERY_FROM_NAV: 'FETCH_QUERY_FROM_NAV',
      FETCH_QUERY_FROM_NAV_STARTED: 'FETCH_QUERY_FROM_NAV_STARTED',
      FETCH_QUERY_FROM_NAV_SUCCESS: 'FETCH_QUERY_FROM_NAV_SUCCESS',
      FETCH_QUERY_FROM_NAV_FAILURE: 'FETCH_QUERY_FROM_NAV_FAILURE',
      SELECT_PRODUCT: 'SELECT_PRODUCT',
      SELECT_PRODUCT_STARTED: 'SELECT_PRODUCT_STARTED',
      SELECT_PRODUCT_SUCCESS: 'SELECT_PRODUCT_SUCCESS',
      SELECT_PRODUCT_FAILURE: 'SELECT_PRODUCT_FAILURE',
      GET_CATALOG_ITEMS: 'GET_CATALOG_ITEMS',
      GET_CATALOG_ITEMS_STARTED: 'GET_CATALOG_ITEMS_STARTED',
      GET_CATALOG_ITEMS_SUCCESS: 'GET_CATALOG_ITEMS_SUCCESS',
      GET_CATALOG_ITEMS_FAILURE: 'GET_CATALOG_ITEMS_FAILURE',
      SELECT_CATALOG_PRODUCT: 'SELECT_CATALOG_PRODUCT',
      SELECT_CATALOG_PRODUCT_STARTED: 'SELECT_CATALOG_PRODUCT_STARTED',
      SELECT_CATALOG_PRODUCT_SUCCESS: 'SELECT_CATALOG_PRODUCT_SUCCESS',
      SELECT_CATALOG_PRODUCT_FINISH: 'SELECT_CATALOG_PRODUCT_FINISH',
      CLEAR_SELECTED_PRODUCT: 'CLEAR_SELECTED_PRODUCT',
      UPDATE_SUGGESTED: 'UPDATE_SUGGESTED'
    });
  });
});
