export default Object.freeze({
  FETCH_QUERY: 'FETCH_QUERY',
  FETCH_QUERY_STARTED: 'FETCH_QUERY_STARTED',
  FETCH_QUERY_SUCCESS: 'FETCH_QUERY_SUCCESS',
  FETCH_QUERY_FAILURE: 'FETCH_QUERY_FAILURE',
  SELECT_PRODUCT: 'SELECT_PRODUCT',
  SELECT_PRODUCT_STARTED: 'SELECT_PRODUCT_STARTED',
  SELECT_PRODUCT_SUCCESS: 'SELECT_PRODUCT_SUCCESS',
  SELECT_PRODUCT_FAILURE: 'SELECT_PRODUCT_FAILURE'
});
